name: Unit Tests

on:
  pull_request:
  push:
    branches: [master]
  workflow_dispatch:

jobs:
  build-and-test:
    name: Build and test
    runs-on: ubuntu-20.04
    steps:
      # Log versions, just for the record.
      - name: Check compiler and cmake versions
        run: |
          g++ --version
          gcc --version
          cmake --version
      
      # Install Qt with this very nice community action.
      - name: Install Qt
        uses: jurplel/install-qt-action@v2
      
      # Checkout our code.
      - name: Checkout Carina
        uses: actions/checkout@v2
        with:
          path: "Carina/"
      
      # Make the build directory.
      - name: Make build directory
        run: |
          cd $GITHUB_WORKSPACE/Carina
          mkdir $GITHUB_WORKSPACE/Carina/build
          
      # Generate the Makefile and build the tests.
      - name: Generate Makefile and build
        run: |
          cd $GITHUB_WORKSPACE/Carina/build
          cmake -S .. -B .
          cmake --build . --target tests
          ls
      
      # Actually run all tests with googletest.
      - name: Run tests
        run: |
          cd $GITHUB_WORKSPACE/Carina/build
          ./tests
